### PR TITLE
Sanjay Krishna Unit 1 Sprint 2

### PR DESCRIPTION
**Pull request by sanjaykmenon**
Incomplete. I am trying to complete it later today and Sunday.

### CODE REVIEW

**Comment by sanjaykmenon** [comment]
Completed the assignment and also did one of the stretch challenges.

**Comment by sanjaykmenon** [comment]
Re-submitting this since I accidentally did it earlier.

**Comment by llpk79** [comment]
## Join and Reshape datasets

 - Join Data Practice
    - First, write down which columns you need and which dataframes have them.
        - This a good idea for future you, or anyone else reading your notebooks.
    - Next, merge these into a single dataframe.
        - 👍 `c_df = pd.merge(df_products, df_orders, on='product_id')`. Saweeeeet!
    - Then, use pandas functions from the previous lesson to get the counts of the top 10 most frequently ordered products.
        - `merged['product_name'].value_counts().head(10)` 
        - `#the idea here is to find out the top 10 ordered products and not from the list.`
        - Sanjay, you did it right there.
        - The groupby solution works as well, might look better charted if sorted first 🤷‍♂ 
- Reshape Data Section
    - ✅ 
- Replicate the lesson code
    - ✅ 
- Complete the code cells we skipped near the beginning of the notebook:
    - Table 2 --> Tidy ✅ 
    - Tidy --> Table 2 ✅ 
     - Nice work here. I like how your make the treatment column more readable.
- Stretch goal
    - Sooooo close. I looks like you lost the top result for the late grouping and the last one for the early is off as well.
    - I think if you approached it a little more systematically, taking only what you need from each table, you'll have it.
    - I also think you've worked on it enough to se an example solution :) [here](https://colab.research.google.com/github/llpk79/DS-Unit-1-Sprint-2-Data-Wrangling-and-Storytelling/blob/master/module1-join-and-reshape-data/Paul_K_Join_and_Reshape_Data.ipynb#scrollTo=mnOuqL9K0dqh)

Very nice work, Sanjay.

**Comment by sanjaykmenon** [comment]
haven;t completed it yet (module 3), just saved.

**Comment by llpk79** [comment]
## Make Explanatory Visualizations

1) Replicate the lesson code. I recommend that you do not copy-paste.
    - Nicely done. Check out [PEP](https://www.python.org/dev/peps/pep-0008/) for proper code formatting.

2) Reproduce another example from FiveThityEight's shared data repository.
    - Where is code?

**Comment by llpk79** [comment]
## Sequence Your Narrative

1. Replicate the Lesson Code
    - Where is visualization?
2. Take it further by using the same gapminder dataset to create a sequence of visualizations that combined tell a story of your choosing.
    - Where is code?

**Pull request closed without merging**
